[language]
name = "Revue CSS"
path_suffixes = ["rcss"]
line_comments = ["//"]
block_comments = [["/*", "*/"]]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
]
word_characters = ["-", "_"]
